services:
  expense-tracker-postgres:
    container_name: expense-tracker-postgres
    image: postgres:17.0
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - expense_tracker_volume:/var/lib/postgresql/data

volumes:
  expense_tracker_volume:
